description = "The student-run magazine of IIIT"
keywords = ""
image = "ping-logo.png"
theme = "dark"
primary_color = "#bb1919"
text_align = "center"
gtag_id = ""
base_url = "https://links.pingiiit.org"

[[sections]]
title = "Articles"
description = "Here are some of our latest articles!"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "UGEE: Thinking? In this economy?"
url = "https://pingiiit.org/2025/07/ugee-thinking-in-this-economy/"
[[sections.items]]
title = "Bro, Remember First Year?"
url = "https://pingiiit.org/2025/06/bro-remember-first-year/"
[[sections.items]]
title = "The number 4 is blue: Musings of an autistic student"
url = "https://pingiiit.org/2025/06/the-number-4-is-blue-musings-of-an-autistic-student/"
[[sections.items]]
title = "Mama, Put My GPTs in the Ground"
url = "https://pingiiit.org/2025/05/mama-put-my-gpts-in-the-ground/"
[[sections.items]]
title = "Have you tried turning the mess off and on again?"
description = "Why exactly do we have a new mess system? The answer is simple. A frog."
url = "https://pingiiit.org/2025/04/have-you-tried-turning-the-mess-off-and-on-again/"
[[sections.items]]
title = "Log Kya Kahenge?"
description = "Imposter Syndrome (/ɪmˈpɒstər ˈsɪn.drəʊm/) – The persistent inability to believe that one’s success is deserved or has been legitimately achieved as a result of one’s efforts or skills."
url = "https://pingiiit.org/2025/04/log-kya-kahenge/"


[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/pingiiit"
[[sections.items]]
title = "Website"
url = "https://www.pingiiit.org"
