description = "The student-run magazine of IIIT"
keywords = ""
image = "ping-logo.png"
theme = "dark"
primary_color = "#bb1919"
text_align = "center"
gtag_id = ""
base_url = "https://links.pingiiit.org"

[[sections]]
title = "Articles"
description = "Here are some of our latest articles!"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "UGEE: Thinking? In this economy?"
description = "In a system wired for ranks and rote, UGEE dares to test something rare — actual thinking."
url = "https://pingiiit.org/2025/07/ugee-thinking-in-this-economy/"
[[sections.items]]
title = "Bro, Remember First Year?"
description = "From JC walks to ghosted group chats — a reflection on friendships and how they change."
url = "https://pingiiit.org/2025/06/bro-remember-first-year/"
[[sections.items]]
title = "The number 4 is blue: Musings of an autistic student"
description = "On Autism Pride Day, one writer reflects on identity, dignity, and what neurodivergence feels like."
url = "https://pingiiit.org/2025/06/the-number-4-is-blue-musings-of-an-autistic-student/"
[[sections.items]]
title = "What does ‘Ee Sala Cup Namdu’ mean for RCB fans?"
description = "RCB’s win shook the city — but for long-time fans, it meant something a little deeper."
url = "https://pingiiit.org/2025/06/what-does-ee-sala-cup-namdu-mean-for-rcb-fans/"
[[sections.items]]
title = "Felicity: The Price of the Party"
description = "Behind the lights, crowds and music is the unseen cost of the fest we love to flaunt."
url = "https://pingiiit.org/2025/06/felicity-the-price-of-the-party/"

[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/pingiiit"
[[sections.items]]
title = "Website"
url = "https://www.pingiiit.org"
